services:
  nextcloud-aio-mastercontainer:
    image: ghcr.io/nextcloud-releases/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_[...]
    network_mode: bridge
    ports:
      - 80:80
      - 8080:8080
      - 8443:8443
    env_file:
      - .env
    environment:
      NEXTCLOUD_OBJECTSTORE_S3_HOST: ${S3_HOST}
      NEXTCLOUD_OBJECTSTORE_S3_BUCKET: ${S3_BUCKET}
      NEXTCLOUD_OBJECTSTORE_S3_KEY: ${S3_KEY}
      NEXTCLOUD_OBJECTSTORE_S3_SECRET: ${S3_SECRET}
      NEXTCLOUD_OBJECTSTORE_S3_PORT: ${S3_PORT}
      NEXTCLOUD_OBJECTSTORE_S3_SSL: ${S3_SSL}
      NEXTCLOUD_OBJECTSTORE_S3_REGION: ${S3_REGION}
      NEXTCLOUD_OBJECTSTORE_S3_AUTOCREATE: ${S3_AUTOCREATE}
      NEXTCLOUD_OBJECTSTORE_S3_USEPATH_STYLE: true
      NEXTCLOUD_DATADIR: s3:// # S3 as default storage

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
  # caddy_certs:
  # caddy_config:
  # caddy_data:
  # caddy_sites:
