services:
  nextcloud:
    image: nextcloud:30.0.2
    restart: always
    ports:
      - 80
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_SECRET_PASSWORD}
      - OVERWRITEPROTOCOL=${NEXTCLOUD_OVERWRITEPROTOCOL}
      # S3/B2 settings
      - OBJECTSTORE_S3_BUCKET=${NEXTCLOUD_S3_BUCKET}
      - OBJECTSTORE_S3_KEY=${NEXTCLOUD_S3_KEY}
      - OBJECTSTORE_S3_SECRET=${NEXTCLOUD_S3_SECRET}
      - OBJECTSTORE_S3_HOST=${NEXTCLOUD_S3_HOST}
      - OBJECTSTORE_S3_PORT=${NEXTCLOUD_S3_PORT}
      - OBJECTSTORE_S3_REGION=${NEXTCLOUD_S3_REGION}
      - OBJECTSTORE_S3_SSL=${NEXTCLOUD_S3_SSL}
      - OBJECTSTORE_S3_AUTOCREATE=${NEXTCLOUD_S3_AUTOCREATE}
      - OBJECTSTORE_S3_USEPATHSTYLE=${NEXTCLOUD_S3_USEPATHSTYLE}

  nextcloud_db:
    image: mariadb
    restart: always
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_SECRET_PASSWORD_ROOT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_SECRET_PASSWORD}

volumes:
  nextcloud_data:
  nextcloud_db_data:

networks:
  dokploy-network:
    external: true
