services:
  nextcloud:
    image: nextcloud:30.0.2
    restart: always
    ports:
      - 80
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_SECRET_PASSWORD}
      - OVERWRITEPROTOCOL=${NEXTCLOUD_OVERWRITEPROTOCOL}
      # S3/B2 settings
      - OBJECTSTORE_S3_BUCKET=${OBJECTSTORE_S3_BUCKET}
      - OBJECTSTORE_S3_KEY=${OBJECTSTORE_S3_KEY}
      - OBJECTSTORE_S3_SECRET=${OBJECTSTORE_S3_SECRET}
      - OBJECTSTORE_S3_HOST=${OBJECTSTORE_S3_HOST}
      - OBJECTSTORE_S3_PORT=${OBJECTSTORE_S3_PORT}
      - OBJECTSTORE_S3_REGION=${OBJECTSTORE_S3_REGION}
      - OBJECTSTORE_S3_SSL=${OBJECTSTORE_S3_SSL}
      - OBJECTSTORE_S3_AUTOCREATE=${OBJECTSTORE_S3_AUTOCREATE}
      - OBJECTSTORE_S3_USEPATH_STYLE=${OBJECTSTORE_S3_USEPATH_STYLE}
      - OBJECTSTORE_S3_STORAGE_CLASS=${OBJECTSTORE_S3_STORAGE_CLASS}
      - OBJECTSTORE_S3_OBJECT_PREFIX=${OBJECTSTORE_S3_OBJECT_PREFIX}
      - OBJECTSTORE_S3_LEGACYAUTH=${OBJECTSTORE_S3_LEGACYAUTH}
      - OBJECTSTORE_S3_SSE_C_KEY=${OBJECTSTORE_S3_SSE_C_KEY}

  nextcloud_db:
    image: mariadb
    restart: always
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_SECRET_PASSWORD_ROOT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_SECRET_PASSWORD}
    networks:
      - dokploy-network

volumes:
  nextcloud_data:
  nextcloud_db_data:

networks:
  dokploy-network:
    external: true
